############################################################################################
# Workflow runs an artillery load test and saves the result in a branch called load-test-results
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      incremental-run:
        required: false
        default: false
        description: "is this an incremental run that should be saved in a timestamped folder?"
        type: boolean
      load-test-folder:
        required: false
        default: "./src/test/artillery/"
        type: string
      load-test-file:
        required: false
        default: "smoketest.yml"
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true
jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        id: prepare
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=test-environment::prime-${GITHUB_REF_NAME,,}-vpc"
    outputs:
      date: ${{ steps.prepare.outputs.date }}
      test-environment: ${{ steps.prepare.outputs.test-environment }}

  load-test:
    needs: [prepare]
    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Checkout load-test-results branch to a loadtest directory nested inside first checkout
        uses: actions/checkout@v2
        with:
          ref: load-test-results
          path: load-test-results

      - name: Make Report Folders
        run: |
          mkdir -p load-test-results/$GITHUB_REF_NAME
          if [[ ${{ inputs.incremental-run }} ]]; then
            mkdir -p load-test-results/$GITHUB_REF_NAME/${{ needs.prepare.outputs.date }}/
          fi

      - name: Run Artillery Test
        working-directory: ${{ inputs.load-test-folder }}
        run: |
          npm install
          artillery run -o report.json -e ${{ needs.prepare.outputs.test-environment }} ${{ inputs.load-test-file }}
          artillery report report.json

      - name: Copy html report
        run: |
          cp ${{ inputs.load-test-folder }}report.json.html load-test-results/$GITHUB_REF_NAME/report.html
          if [[ ${{ inputs.incremental-run }} ]]; then
            cp ${{ inputs.load-test-folder }}report.json.html load-test-results/$GITHUB_REF_NAME/${{ needs.prepare.outputs.date }}/report.html
          fi
          cd load-test-results/$GITHUB_REF_NAME
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'pubfactory-service'
            git config --global user.email 'noreply@pubfactory.com'
            git add -A
            git commit -m "Autogenerated load test report"
            git push
          fi

      - name: Send ${{ job.status }} message to prime-chatops room
        uses: act10ns/slack@v1.5.1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#prime-chatops'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send ${{ job.status }} message to prime room
        uses: act10ns/slack@v1.5.1
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

