############################################################################################
# Workflow runs an artillery load test and saves the result in a branch called load-test-results
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      incremental-run:
        required: false
        default: false
        description: "is this an incremental run that should be saved in a timestamped folder?"
        type: boolean
      load-test-folder:
        required: false
        default: "./src/test/artillery/"
        type: string
      load-test-file:
        required: false
        default: "smoketest.yml"
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true
jobs:

  load-test:
    runs-on: [self-hosted, ubuntu]
    timeout-minutes: 15

    steps:
      - name: Preparing
        id: prepare
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "test-environment=prime-${GITHUB_REF_NAME,,}-vpc" >> $GITHUB_OUTPUT

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout load-test-results branch to a loadtest directory nested inside first checkout
        uses: actions/checkout@v3
        with:
          ref: load-test-results
          path: load-test-results

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '14'

      - name: Make Report Folders
        run: |
          mkdir -p load-test-results/$GITHUB_REF_NAME

      - name: Make incremental report folder
        if:  ${{ inputs.incremental-run }}
        run: |
          mkdir -p load-test-results/$GITHUB_REF_NAME/${{ steps.prepare.outputs.date }}/

      - name: Run Artillery Test
        if: ${{ hashFiles(format('{0}{1}', inputs.load-test-folder, inputs.load-test-file)) != '' }}
        run: |
          cd ${{ inputs.load-test-folder }}
          npm install -g artillery@2.0.0-27
          npm install -g artillery-plugin-expect@2.1.0
          npm install
          artillery run -o report.json -e ${{ steps.prepare.outputs.test-environment }} ${{ inputs.load-test-file }} --insecure
          artillery report report.json

      - name: Copy report
        if: ${{ hashFiles(format('{0}report.json', inputs.load-test-folder)) != '' }}
        run: |
          cp ${{ inputs.load-test-folder }}report.json load-test-results/$GITHUB_REF_NAME/report.json
          cp ${{ inputs.load-test-folder }}report.json.html load-test-results/$GITHUB_REF_NAME/report.html

      - name: Copy incremental report
        if: ${{ inputs.incremental-run && hashFiles(format('{0}report.json', inputs.load-test-folder)) != '' }}
        run: |
          cp ${{ inputs.load-test-folder }}report.json load-test-results/$GITHUB_REF_NAME/${{ steps.prepare.outputs.date }}/report.json
          cp ${{ inputs.load-test-folder }}report.json.html load-test-results/$GITHUB_REF_NAME/${{ steps.prepare.outputs.date }}/report.html

      - name: Commit reports
        run: |
          cd load-test-results/$GITHUB_REF_NAME
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'pubfactory-service'
            git config --global user.email 'noreply@pubfactory.com'
            git add -A
            git commit -m "Autogenerated load test report"
            git push
          fi

      - name: Send ${{ job.status }} message to prime-chatops room
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#prime-chatops'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send ${{ job.status }} message to prime room
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

