############################################################################################
# Workflow that checks out code, builds, and pushes a native docker image
#
# By: JGF
############################################################################################

name: Build ARM64 Native Image

on:
  workflow_call:
    secrets:
      MAVEN_SETTINGS:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      SLACK_WEBHOOK:
        required: true
      RUNS_ON_OS:
        required: true
      JAVA_DISTROBUTION:
        required: true
      JAVA_VERSION:
        required: true

jobs:
  build:

    runs-on: ${{ secret.RUNS_ON_OS }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK ${{ secret.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ secret.JAVA_VERSION }}
          distribution: ${{ secret.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Set up GraalVm
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: ${{ secret.GRAALVM_VERSION }}
          java: java${{ secret.JAVA_VERSION }}
          arch: 'aarch64'

      - name: Log into docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platform: linux/arm64

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
          cp -rf ~/.m2/ ${PWD}/.mvn/wrapper/.m2
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Buid native binary
        run: docker buildx build --platform linux/arm64 --push -f src/main/docker/Dockerfile.native -t pubfactory/prime-landing:dev-arm64 .

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'GitBot'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Build Failure'