############################################################################################
# Workflow that checks out code, builds, and pushes a native docker image
#
# By: JGF
############################################################################################

name: Build ARM64 Native Image

on:
  workflow_call:
    inputs:
      notify-slack-channel:
        description: 'the slack channel to notify on failure'
        default: 'prime'
        required: false
        type: string
    secrets:
      MAVEN_SETTINGS:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      SLACK_WEBHOOK_API_KEY:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Log into docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platform: linux/arm64

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
          cp -rf ~/.m2/ ${PWD}/.mvn/wrapper/.m2
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Buid native binary
        run: docker buildx build --platform linux/arm64 --push -f src/main/docker/Dockerfile.multistage -t pubfactory/prime-landing:dev-arm64 .

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_API_KEY }}
          SLACK_CHANNEL: ${{ inputs.notify-slack-channel }}
          SLACK_USERNAME: 'GitBot'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Build Failure'