############################################################################################
# Workflow that checks out code, builds, and pushes a native docker image
#
# By: JGF
############################################################################################

name: Build AMD64 Native Image

on:
    workflow_call:
        secrets:
            MAVEN_SETTINGS:
                required: true
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_PASSWORD:
                required: true

jobs:

    build-native-image:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
            uses: actions/checkout@v2

        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                  ${{ runner.os }}-maven-

          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
                java-version: '11'
                distribution: 'adopt'
                cache: maven

          - name: Log into docker
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1

          - name: Override maven settings.xml
            run: |
                echo $MAVEN_SETTINGS > ~/.m2/settings.xml
            shell: bash
            env:
                MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

        - name: Maven build navite binary
          run: mvn package -DskipTests -Pnative -Dquarkus.native.container-build=true

        - name: Build docker image
          run: |
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            docker build -f src/main/docker/Dockerfile.native -t $GITHUB_REPOSITORY:$GITHUB_REF_NAME-latest -t $GITHUB_REPOSITORY:$GITHUB_REF_NAME-$git_hash .
            docker push $GITHUB_REPOSITORY:$GITHUB_REF_NAME-latest
            docker push $GITHUB_REPOSITORY:$GITHUB_REF_NAME-$git_hash