############################################################################################
# Workflow that checks out code, builds, and pushes a native docker image
#
# By: JGF
############################################################################################

name: Build ARM64 Native Image

on:
  workflow_call:
    secrets:
      MAVEN_SETTINGS:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      SLACK_WEBHOOK:
        required: true
      JAVA_DISTROBUTION:
        required: true
      JAVA_VERSION:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Git Branch
        if: github.event.action == 'upstream-job-success'
        run: |
          echo "Recieved upstream-job-success message from ${{ github.event.client_payload.repository }} on branch ${{ github.event.client_payload.branch }}"
          echo "GITHUB_REF_NAME=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ secrets.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          distribution: ${{ secrets.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Log into docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platform: linux/arm64

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
          cp -rf ~/.m2/ ${PWD}/.mvn/wrapper/.m2
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Maven build native binary
        run: mvn -U clean package -DskipTests -Pnative

      - name: Buid native binary
        run: docker buildx build --platform linux/arm64 --push -f src/main/docker/Dockerfile.multistage -t pubfactory/prime-landing:dev-arm64 .

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'GitBot'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Build Failure'

      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'prime-chatops'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'GitBot'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Build Success'