############################################################################################
# Workflow that checks out code, runs `mvn versions:set-property` and commits changes
#
# By: JGF
############################################################################################

name: Maven Update Property

on:
  workflow_call:
    inputs:
      property:
        description: "the maven property to update"
        required: true
        type: string
      value:
        description: "the value to set the property to"
        required: true
        type: string
    secrets:
      MAVEN_SETTINGS:
        required: true
      SLACK_WEBHOOK:
        required: true
      JAVA_DISTRIBUTION:
        required: true
      JAVA_VERSION:
        required: true
    outputs:
      property-updated:
        description: "if the job updated the property"
        value: ${{ jobs.update-property.outputs.property-updated }}

jobs:

  update-property:
    runs-on: ubuntu-latest
    if: ${{ inputs.value != '' && inputs.property != '' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ secrets.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          distribution: ${{ secrets.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Set Maven Property
        run: |
          echo "updating maven proprety ${{ inputs.property }} to value ${{ inputs.value }}"
          mvn versions:set-property -Dproperty=${{ inputs.property }} -DnewVersion=${{ inputs.value }}

      - name: Commit (if it changed)
        id: commit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'pubfactory-service'
            git config --global user.email 'noreply@pubfactory.com'
            git add -A
            git commit -m "Bumping property ${{ inputs.property }} to ${{ inputs.value }}"
            git push
            echo "::set-output name=property-updated::true"
          fi

    outputs:
      property-updated: ${{ steps.commit.outputs.property-updated }}
