############################################################################################
# Workflow that checks out code, runs `mvn versions:set-property` and commits changes
#
# By: JGF
############################################################################################

name: Maven Update Property

on:
  workflow_call:
    secrets:
      MAVEN_SETTINGS:
        required: true
      SLACK_WEBHOOK:
        required: true
      JAVA_DISTRIBUTION:
        required: true
      JAVA_VERSION:
        required: true

jobs:

  update-property:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ secrets.JAVA_VERSION }}
        uses: actions/setup-java@v3.4.0
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          distribution: ${{ secrets.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Determine Update Rules
        id: update-rules
        run: |
          if [[ ${{ env.GITHUB_REF_NAME == github.event.repository.default_branch }} ]]; then
            echo "Default branches should allow major update, allow minor updates, and allow snapshots"
            echo "::set-output name=allow-major-updates::true"
            echo "::set-output name=allow-minor-updates::true"
            echo "::set-output name=allow-snapshots::true"
          else
            echo "Non default branches are assumed to be release branches and should not allow major update, should allow minor updates, and should not allow snapshots"
            echo "::set-output name=allow-major-updates::false"
            echo "::set-output name=allow-minor-updates::true"
            echo "::set-output name=allow-snapshots::false"
          fi

      - name: Update Maven Properties
        run: |
          echo "updating maven properties for dependencies that match com.pubfactory*"
          mvn -U versions:update-properties -DallowMajorUpdates=${{ steps.update-rules.outputs.allow-major-updates }} -DallowMinorUpdates=${{ steps.update-rules.outputs.allow-minor-updates }} -DallowSnapshots=${{ steps.update-rules.outputs.allow-snapshots }} -Dincludes=com.pubfactory*

      - name: Commit (if it changed)
        id: commit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'pubfactory-service'
            git config --global user.email 'noreply@pubfactory.com'
            git add -A
            git commit -m "Bumping prime dependencies"
            git push
            echo "::set-output name=property-updated::true"
          fi
