############################################################################################
# Workflow that checks out code, runs `mvn versions:set-property` and commits changes
#
# By: JGF
############################################################################################

name: Maven Update Property

on:
  workflow_call:
    secrets:
      MAVEN_SETTINGS:
        required: true
      SLACK_WEBHOOK:
        required: true
      JAVA_DISTRIBUTION:
        required: true
      JAVA_VERSION:
        required: true

jobs:

  update-property:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ secrets.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
          distribution: ${{ secrets.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Determine Update Rules
        run: |
          echo "${{ toJson(github.event) }}"

      - name: Update Maven Properties
        run: |
          echo "updating maven properties for dependencies that match com.pubfactory.prime"
          mvn versions:update-properties -DallowSnapshots=true -Dincludes=com.pubfactory.prime

      - name: Commit (if it changed)
        id: commit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'pubfactory-service'
            git config --global user.email 'noreply@pubfactory.com'
            git add -A
            git commit -m "Bumping property ${{ inputs.property }} to ${{ inputs.value }}"
            git push
            echo "::set-output name=property-updated::true"
          fi
