name: Maven unit test

on:
  workflow_call:
    inputs:
      commit-jacoco-badge:
        description: 'Do you want to commit the jacoco badge after generating code coverage data?'
        default: true
        required: false
        type: boolean
      jacoco-csv-file:
        description: 'the file or files to consider when calculating code coverage'
        default: 'target/jacoco-report/jacoco.csv'
        required: false
        type: string
    secrets:
      MAVEN_SETTINGS:
        required: true

jobs:

  unit-test:

    runs-on: ubuntu-latest

    env:
      BADGES_DIR: $GITHUB_REF_NAME/badges

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Maven run unit tests
        run: mvn clean test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: ${{ env.BADGES_DIR }}
          generate-summary: true
          on-missing-report: quiet
          fail-if-coverage-less-than: 75
          jacoco-csv-file: target/jacoco-report/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ ${{ inputs.commit-jacoco-badge }} ]]; then
            ls -l
            cd $GITHUB_REF_NAME/badges
            if [[ `git status --porcelain` ]]; then
              git config --global user.name 'pubfactory-service'
              git config --global user.email 'noreply@pubfactory.com'
              git add -A
              git commit -m "Autogenerated JaCoCo coverage badge"
              git push
            fi
          fi
          if [[ ${{ inputs.commit-jacoco-badge }} ]]; then
            echo "configured not to commit badge"
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: >
            target/jacoco-report/
            $GITHUB_REF_NAME/badges/