############################################################################################
# Workflow that checks out code, runs `mvn versions:set-property` and commits changes
#
# By: JGF
############################################################################################

name: Maven Update Property

on:
  workflow_call:
    inputs:
      property:
        description: "the maven property to update"
        required: true
        type: string
      value:
        description: "the value to set the property to"
        required: true
        type: string
    secrets:
      MAVEN_SETTINGS:
        required: true
    outputs:
      property-updated:
        description: "if the job updated the property"
        value: ${{ jobs.update-property.property-updated }}

jobs:

  update-property:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Override maven settings.xml
        run: |
          echo $MAVEN_SETTINGS > ~/.m2/settings.xml
        shell: bash
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Set Maven Property
        run: |
          echo "updating maven proprety ${{ inputs.property }} to value ${{ inputs.value }}"
          mvn versions:set-property -Dproperty=${{ inputs.property }} -DnewVersion=${{ inputs.value }}

      - name: Commit (if it changed)
        id: commit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'pubfactory-service'
            git config --global user.email 'noreply@pubfactory.com'
            git add -A
            git commit -m "Bumping property ${{ inputs.property }} to ${{ inputs.value }}"
            git push
            echo "::set-output name=property-updated::true"
          fi
    outputs:
      property-updated: ${{ steps.commit.property-updated }}