############################################################################################
# Workflow that does a nomad deployment and waits for the result
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        description: "Name of the job to deploy"
        type: string
    secrets:
      NOMAD_TOKEN:
        required: true
      NOMAD_ADDRESS:
        required: true
      NOMAD_JOB_REPOSITORY:
        required: true
      LEVANT_CONFIG:
        required: true
      GIT_ACCESS_TOKEN:
        required: true

jobs:

  nomad-deploy:

    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Get job definition
        run:
          curl -K ${{ secrets.NOMAD_ADDRESS }}/v1/job/${{ inputs.job-name }} >> ./${{ inputs.job-name }}.json ;
          cat ./${{ inputs.job-name}}.json ;
          curl --request POST --data ./${{ inputs.job-name}}.json ${{ secrets.NOMAD_ADDRESS }}/v1/jobs ;

      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action@v1
        with:
          nomad-addr: ${{ secrets.NOMAD_ADDRESS }}
          nomad-token: ${{ secrets.NOMAD_TOKEN }}
          nomad-job-name: ${{ inputs.job-name }}