############################################################################################
# Workflow that does a nomad deployment and waits for the result
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        description: "Name of the job to deploy"
        type: string
      nomad-address:
        required: true
        type: string
jobs:

  nomad-deploy:

    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Get job definition
        run: |
          touch /tmp/${{ inputs.job-name }}.json
          curl -K ${{ inputs.nomad-address }}/v1/job/${{ inputs.job-name }} >> /tmp/${{ inputs.job-name }}.json

      - run: cat ./${{ inputs.job-name}}.json

      - name: Redeploy Job
        run: curl --request POST --data /tmp/${{ inputs.job-name}}.json ${{ inputs.nomad-address }}/v1/jobs

      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action@v1
        with:
          nomad-addr: ${{ inputs.NOMAD_ADDRESS }}
          nomad-token: ${{ secrets.NOMAD_TOKEN }}
          nomad-job-name: ${{ inputs.job-name }}