############################################################################################
# Workflow that does a nomad deployment and waits for the result
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        description: "Name of the job to deploy"
        type: string
      docker-tag:
        required: false
        description: "docker tag to deploy"
        type: string
    secrets:
      NOMAD_ADDRESS:
        required: true
      NOMAD_JOB_REPOSITORY:
        required: true
      GIT_ACCESS_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: true
jobs:

  nomad-deploy:

    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Checkout Nomad Jobs Repo
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: ${{ secrets.NOMAD_JOB_REPOSITORY }}

      - name: Deploy default tag
        if: ${{ inputs.docker-tag == '' }}
        run: nomad job run -address=${{ secrets.NOMAD_ADDRESS }} ./${{ inputs.job-name }}.nomad

      - name: Deploy tag ${{ inputs.docker-tag }}
        if: ${{ inputs.docker-tag }}
        run: nomad job run -address=${{ secrets.NOMAD_ADDRESS }} -var=docker-tag=${{ inputs.docker-tag }} ./${{ inputs.job-name }}.nomad

      - name: Send success message to slack
        uses: act10ns/slack@v1.5.0
        if: ${{ success() }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#prime-chatops'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRIME_ROOM_WEBHOOK }}

      - name: Send ${{ job.status }} message to slack
        uses: act10ns/slack@v1.5.0
        if: ${{ !success() }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRIME_ROOM_WEBHOOK }}
