############################################################################################
# Workflow that does a nomad deployment and waits for the result
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        description: "Name of the job to deploy"
        type: string
      docker-tag:
        required: false
        description: "docker tag to deploy"
        type: string
    secrets:
      NOMAD_ADDRESS:
        required: true
      NOMAD_JOB_REPOSITORY:
        required: true
      GIT_ACCESS_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: true
jobs:

  nomad-deploy:

    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Checkout Nomad Jobs Repo
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: ${{ secrets.NOMAD_JOB_REPOSITORY }}

      - name: Deploy default tag
        if: ${{ inputs.docker-tag == '' }}
        run: nomad job run -address=${{ secrets.NOMAD_ADDRESS }} ./${{ inputs.job-name }}.nomad

      - name: Deploy tag ${{ inputs.docker-tag }}
        if: ${{ inputs.docker-tag }}
        run: nomad job run -address=${{ secrets.NOMAD_ADDRESS }} -var=docker-tag=${{ inputs.docker-tag }} ./${{ inputs.job-name }}.nomad

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'GitBot'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Deployment Failure: ${{ inputs.job-name }} - ${{ inputs.docker-tag }}'

      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'prime-chatops'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'GitBot'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Deployment Successful: ${{ inputs.job-name }} - ${{ inputs.docker-tag }}'
