############################################################################################
# Workflow that does a nomad deployment and waits for the result
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        description: "Name of the job to deploy"
    secrets:
      NOMAD_TOKEN:
        required: true
      NOMAD_ADDRESS:
        required: true
      NOMAD_JOB_REPOSITORY:
        required: true;
      LEVANT_CONFIG:
        required: true;
      GIT_ACCESS_TOKEN:
        required: true;

jobs:

  nomad-deploy:

    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Checkout Nomad Jobs Repo
        uses: actions/checkout
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: ${{ secrets.NOMAD_JOB_REPOSITORY }}

      - name: Deploy with Nomad
        uses: qazz92/nomad-deploy
        with:
          token: ${{ secrets.NOMAD_TOKEN }}
          address: ${{ secrets.NOMAD_ADDRESS }}
          job: ${{ inputs.job-name }}.nomad
          config: ${{ secrets.LEVANT_CONFIG }}

      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action
        with:
          nomad-addr: ${{ secrets.NOMAD_ADNOMAD_ADDRESSDR }}
          nomad-token: ${{ secrets.NOMAD_TOKEN }}
          nomad-job-name: ${{ inputs.job-name }}