############################################################################################
# Workflow that does a nomad deployment and waits for the result
#
# By: JGF
############################################################################################

name: Nomad Deployment

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        description: "Name of the job to deploy"
        type: string
    secrets:
      NOMAD_ADDRESS:
        required: true
jobs:

  nomad-deploy:

    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Get job definition
        run: |
          touch /tmp/${{ inputs.job-name }}.json
          curl ${{ secrets.NOMAD_ADDRESS }}/v1/job/${{ inputs.job-name }} >> /tmp/${{ inputs.job-name }}.json

      - run: cat /tmp/${{ inputs.job-name}}.json

      - name: Redeploy Job
        run: curl --request POST --data @/tmp/${{ inputs.job-name}}.json ${{ secrets.NOMAD_ADDRESS }}/v1/jobs

      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action@v1
        with:
          nomad-addr: ${{ inputs.NOMAD_ADDRESS }}
          nomad-token: ${{ secrets.NOMAD_TOKEN }}
          nomad-job-name: ${{ inputs.job-name }}